#!/bin/bash
docker run -it --rm --name astra --network host \
   -e "SKIP_KUBE_CONTEXT_CHECK=true" \
   -e "DEPLOY_TYPE=dev" \
   -e "WORKDIR=/home/work/astra" \
   -e "HOSTWORKDIR=/tmp/astra" \
   -e "VAULT_ADDR=${VAULT_ADDR}" \
   -e "GITHUB_USERNAME=${GITHUB_ID}" \
   -e "GITHUB_TOKEN=${GITHUB_TOKEN}" \
   -e "GITHUB_ID=${GITHUB_ID}" \
   -e "DH_ID=${DH_ID}" \
   -e "DH_TOKEN=${DH_TOKEN}" \
   -e "CREDS_AUTH_CLIENT_ID=${CREDS_AUTH_CLIENT_ID}" \
   -e "CREDS_AUTH_DOMAIN=${CREDS_AUTH_DOMAIN}" \
   -e "CREDS_ISSUER_URL=${CREDS_ISSUER_URL}" \
   -e "IMAGE_HOST=${IMAGE_HOST}" \
   -e "CLUSTER_ENDPOINT=${CLUSTER_ENDPOINT}" \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v /tmp/astra:/home/work/astra \
   -v $(pwd):/home/polaris -v ${HOME}/.kube:/home/.kube \
   ghcr.io/netapp-polaris/polaris/astra/astradt:v0.1.0 time astra $@
