#!/bin/bash
# If the script fails to pull image from jfrog, most likely that you do not have
# permission to pull from jfrog, you may contact Jeremy Harrod for access to jfrog

function getConnectorImages() {
  echo "Ready to pull astra connector images..."
  prefix=$1
  if [[ -z $prefix ]]; then
    prefix="netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune/"
  fi
  cimages=(
    'controller'
    'exechook'
    'resourcebackup'
    'resourcedelete'
    'resourcerestore'
    'resourcesummaryupload'
    'restic'
    'kopia'
    'astra-connector'
    'kube-rbac-proxy:v0.14.1'
    'trident-autosupport:24.1.1-custom'
  )

  for cimage in "${cimages[@]}"; do
    echo "Pulling image ${prefix}${cimage}..."
    docker pull ${prefix}${cimage} >/dev/null 2>&1 || null
    docker tag ${prefix}${cimage} localhost:5001/${cimage} >/dev/null 2>&1 || null
    docker tag ${prefix}${cimage} ${cimage} >/dev/null 2>&1 || null
  done
}

getConnectorImages $@
