#!/bin/bash

function getConnectorImages() {
  echo "Ready to pull some images"
  prefix="netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune/"
  if [[ -f /tmp/astra3/neptune-images.list ]]; then
    filecontent=$(cat /tmp/astra3/neptune-images.list)
    cimages=($(echo $filecontent))
  else
    cimages=(
      'controller'
      'exechook'
      'resourcebackup'
      'resourcedelete'
      'resourcerestore'
      'resourcesummaryupload'
      'restic'
      'astra-connector'
      'nats:2.8.4-alpine3.15'
      'natssync-client:2.1.202309262120'
    )
  fi

  # These are the best effort, since these can change quite a lot, also assumed that
  # the jfrog images have already been downloaded
  for cimage in "${cimages[@]}"; do
    echo "Pulling image ${prefix}${cimage}..."
    docker pull ${prefix}${cimage} >/dev/null 2>&1 || null
    docker tag ${prefix}${cimage} localhost:5001/${cimage} >/dev/null 2>&1 || null
    docker tag ${prefix}${cimage} ${cimage} >/dev/null 2>&1 || null
  done
}

getConnectorImages
