#!/bin/bash
function pushConnectorImages() {
  # always tag the latest image available locally onto the target repo
  # with the tag passed as parameter
  tag=$1
  prefix=$2

  if [[ -z $tag ]]; then
    tag="latest"
  fi

  if [[ -z $prefix ]]; then
    if [[ -z $GITHUB_ID ]]; then
      prefix="ghcr.io/litong01/neptune/"
    else
      prefix="ghcr.io/${GITHUB_ID}/neptune/"
    fi
  fi
  echo "Ready to push astra connector images..."

  cimages=(
    'controller'
    'exechook'
    'resourcebackup'
    'resourcedelete'
    'resourcerestore'
    'resourcesummaryupload'
    'restic'
    'astra-connector'
    'nats:2.8.4-alpine3.15'
    'natssync-client:2.1.202309262120'
    'kube-rbac-proxy:v0.14.1'
    'trident-autosupport:24.1.1-custom'
  )

  # These are the best effort, since these can change quite a lot, also assumed that
  # the jfrog images have already been downloaded
  for cimage in "${cimages[@]}"; do
    echo "Pushing image ${prefix}${cimage}..."
    IFS=$':' PARTS=($(echo "${cimage}")) && IFS=$' '
    if [[ -z "${PARTS[1]}" ]]; then
      docker tag ${cimage}:latest ${prefix}${cimage}:${tag}
      docker push ${prefix}${cimage}:${tag}
    else
      docker tag ${cimage} ${prefix}${cimage}
      docker push ${prefix}${cimage}
    fi
  done
}

pushConnectorImages $@
