apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  accountName: Example
  astraVersion: 1619-integration
  astraAddress: integration.astra.netapp.io
  autoSupport:
    enrolled: true
    url: https://stagesupport.netapp.com/asupprod/post/1.0/postAsup
  email: admin@integration.astra.netapp.io
  firstName: SRE
  lastName: Admin
  imageRegistry:
    name: kind-registry:5001
    secret: ""
  astraResourcesScaler: Default
  crds: {}
  ingressType: AccTraefik
  scaleSize: Small
  additionalValues:
    activity:
      replicas: 1
    polaris-mongodb:
      mongodb:
        persistence:
          size: 5Gi
        replicaCount: 1
        image:
          registry: ghcr.io
          tag: 5.0.14
          repository: zcube/bitnami-compat/mongodb
    polaris-consul:
      consul:
        server:
          replicas: 1
          bootstrapExpect: 1
          storage: 2Gi
          resources:
            limits:
              memory: 50Mi
    keycloak-operator:
      replicaCount: 1
    polaris-keycloak:
      replicaCount: 1
      mariadb-galera:
        replicaCount: 1
    features:
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 40Mi
    loki:
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    asup:
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    nautilus:
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    polaris-influxdb2:
      persistence:
        size: 5Gi
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    traefik:
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    task-service:
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    nats:
      replicaCount: 1
      auth:
        enabled: true
    polaris-vault:
      vault:
        server:
          ha:
            replicas: 1
          auditStorage:
            size: 2Gi
    certificates:
      replicas: 1
    credentials:
      replicas: 1
    krakend:
      replicas: 1
    openapi:
      replicas: 1
    vault-controller:
      replicas: 1
    cert-manager:
      cert-manager:
        replicaCount: 1
        webhook:
          replicaCount: 1
        cainjector:
          replicaCount: 1
