apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra 
spec:
  accountName: "Example"
  astraVersion: "1619-integration"
  astraAddress: "astra.example.com"
  # astraKubeConfigSecret is set to name of the secret which contains kubeconfig of the ACC cluster
  # secret needs to be created prior to deploying ACC if you want it to be managed by Astra
  # astraKubeConfigSecret: "acc-kubeconfig-cred"
  autoSupport:
    enrolled: true
    # url is set to staging. url field should not be exposed to customers (defaults to prod if not set) # delete_in_NSS
    url: "https://stagesupport.netapp.com/asupprod/post/1.0/postAsup"  # delete_in_NSS
  email: "admin@astra.example.com"
  firstName: "SRE"
  lastName: "Admin"
  imageRegistry:
    name: "kind-registry:5001"
