apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  2;
    events {
      worker_connections  4096;
    }
    stream {
      server {
        listen 5001 ssl;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        proxy_pass  172.18.0.3:5000;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 5001
    protocol: TCP
    name: https
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: secure-testing-cert
      - name: config-volume
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:1.23.4
        ports:
        - containerPort: 5001
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
