---
apiVersion: v1
kind: Service
metadata:
  name: kind-registry
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kind-registry
subsets:
  - addresses:
      - ip: 100
    ports:
      - port: 5000
