apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: test-appvault1
spec:
  providerType: generic-s3
  providerConfig:
    endpoint: minio.astra-connector.svc:9000
    accessKeyId: minioadmin
    secretAccessKey: minioadmin
    bucketName: minio-bucket
    secure: "false"