---
apiVersion: v1
kind: Secret
metadata:
  name: test-appvault-secret1
type: Opaque
data:
  accessKeyId: bWluaW9hZG1pbg==
  secretAccessKey: bWluaW9hZG1pbg==
---
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: test-appvault1
spec:
  providerType: generic-s3
  providerConfig:
    endpoint: minio.astra-connector.svc:9000
    bucketName: minio-bucket
    skipCertValidation: "true"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: test-appvault-secret1
        key: accessKeyId
    secretAccessKey:
      valueFromSecret:
        name: test-appvault-secret1
        key: secretAccessKey
