apiVersion: v1
kind: Secret
metadata:
  name: neptune-resource-summary-upload-secret
type: Opaque
data:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuYXV0aDAuY29tLyIsImF1ZCI6Imh0dHBzOi8vYXBpLmV4YW1wbGUuY29tL2NhbGFuZGFyL3YxLyIsInN1YiI6InVzcl8xMjMiLCJpYXQiOjE0NTg3ODU3OTYsImV4cCI6MTQ1ODg3MjE5Nn0.CA7eaHjIHz5NxeIJoFK9krqaeZrPLwmMmgI_XiQiIkQ
---
apiVersion: management.astra.netapp.io/v1alpha1
kind: ResourceSummaryUpload
metadata:
  labels:
    app.kubernetes.io/name: resourcesummaryupload
    app.kubernetes.io/instance: resourcesummaryupload-sample
    app.kubernetes.io/part-of: neptune
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: neptune
  name: resourcesummaryupload-sample
spec:
  pushEndpoint: "https://whatever.com"
  secretRef: "neptune-resource-summary-upload-secret"
  dataSourceRef:
    apiGroup: management.astra.netapp.io
    kind: Snapshot
    name: test-snapshot1


