apiVersion: v1
kind: Secret
metadata:
  name: neptune-resource-summary-upload-secret
type: Opaque
data:
  token: bXlzZWNyZXQ=
---
apiVersion: management.astra.netapp.io/v1alpha1
kind: ResourceSummaryUpload
metadata:
  labels:
    app.kubernetes.io/name: resourcesummaryupload
    app.kubernetes.io/instance: resourcesummaryupload-sample
    app.kubernetes.io/part-of: neptune
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: neptune
  name: resourcesummaryupload-sample
spec:
  pushEndpoint: "https://pathecho-31056.neptune-system.svc:31056/post/"
  pushToken:
    valueFromSecret:
      name: "neptune-resource-summary-upload-secret"
      key: "token"
  skipCertValidation: true
  dataSourceRef:
    apiGroup: management.astra.netapp.io
    kind: Snapshot
    name: test-snapshot1


