---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldapconfig
data:
  inetorgperson.ldif: |
    dn: cn=inetorgperson,cn=schema,cn=config
    objectClass: olcSchemaConfig
    cn: inetorgperson
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.1 NAME 'carLicense' DESC 'RFC279
     8: vehicle license or registration plate' EQUALITY caseIgnoreMatch SUBSTR cas
     eIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.2 NAME 'departmentNumber' DESC '
     RFC2798: identifies a department within an organization' EQUALITY caseIgnoreM
     atch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.241 NAME 'displayName' DESC 'RFC
     2798: preferred name to be used when displaying entries' EQUALITY caseIgnoreM
     atch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SI
     NGLE-VALUE )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.3 NAME 'employeeNumber' DESC 'RF
     C2798: numerically identifies an employee within an organization' EQUALITY ca
     seIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.12
     1.1.15 SINGLE-VALUE )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.4 NAME 'employeeType' DESC 'RFC2
     798: type of employment for a person' EQUALITY caseIgnoreMatch SUBSTR caseIgn
     oreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
    olcAttributeTypes: ( 0.9.2342.19200300.100.1.60 NAME 'jpegPhoto' DESC 'RFC2
     798: a JPEG image' SYNTAX 1.3.6.1.4.1.1466.115.121.1.28 )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.39 NAME 'preferredLanguage' DESC
     'RFC2798: preferred written or spoken language for a person' EQUALITY caseIg
     noreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.
     15 SINGLE-VALUE )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.40 NAME 'userSMIMECertificate' D
     ESC 'RFC2798: PKCS#7 SignedData used to support S/MIME' SYNTAX 1.3.6.1.4.1.14
     66.115.121.1.5 )
    olcAttributeTypes: ( 2.16.840.1.113730.3.1.216 NAME 'userPKCS12' DESC 'RFC2
     798: personal identity information, a PKCS #12 PFX' SYNTAX 1.3.6.1.4.1.1466.1
     15.121.1.5 )
    olcAttributeTypes: (1.2.840.113556.1.4.656
      NAME ( 'userPrincipalName' )
      DESC 'RFC822: user principal name'
      EQUALITY caseIgnoreIA5Match
      SUBSTR caseIgnoreIA5SubstringsMatch
      SYNTAX 1.3.6.1.4.1.1466.115.121.1.26{128} )
    olcObjectClasses: ( 2.16.840.1.113730.3.2.2 NAME 'inetOrgPerson' DESC 'RFC2
     798: Internet Organizational Person' SUP organizationalPerson STRUCTURAL MAY
     ( audio $ businessCategory $ carLicense $ departmentNumber $ displayName $ em
     ployeeNumber $ employeeType $ givenName $ homePhone $ homePostalAddress $ ini
     tials $ jpegPhoto $ labeledURI $ mail $ manager $ mobile $ o $ pager $ photo
     $ roomNumber $ secretary $ uid $ userCertificate $ x500uniqueIdentifier $ pre
     ferredLanguage $ userSMIMECertificate $ userPKCS12 $ userPrincipalName) )
  users.ldif: |
    # LDIF Export for dc=example,dc=org
    # Server: openldap (openldap)
    # Search Scope: sub
    # Search Filter: (objectClass=*)
    # Total Entries: 10
    #
    # All user passwords are admin
    # admin and admint password are both adminpassword
    # Version: 1.2.3

    version: 1

    ## Entry 1: dc=example,dc=org
    dn: dc=example,dc=org
    dc: example
    o: "MyExample Inc."
    objectclass: top
    objectclass: dcObject
    objectclass: organization

    ## Entry 2: cn=admint,dc=example,dc=org
    dn: cn=admint,dc=example,dc=org
    cn: admint
    description: LDAP administrator
    objectclass: simpleSecurityObject
    objectclass: organizationalRole
    userpassword: {SSHA}iGmwNRRDcGxmafPklI1kcKivNq8cCb4j

    # Entry 3: ou=groups,dc=example,dc=org
    dn: ou=groups,dc=example,dc=org
    objectclass: organizationalUnit
    objectclass: top
    ou: groups

    # Entry 4: cn=admin,ou=groups,dc=example,dc=org
    dn: cn=admin,ou=groups,dc=example,dc=org
    cn: admin
    gidnumber: 501
    memberuid: 1003
    objectclass: posixGroup
    objectclass: top
    userpassword: {SSHA}iGmwNRRDcGxmafPklI1kcKivNq8cCb4j

    # Entry 5: cn=developers,ou=groups,dc=example,dc=org
    dn: cn=developers,ou=groups,dc=example,dc=org
    cn: developers
    gidnumber: 500
    memberuid: 1000
    memberuid: 1001
    memberuid: 1002
    objectclass: posixGroup
    objectclass: top

    # Entry 6: ou=users,dc=example,dc=org
    dn: ou=users,dc=example,dc=org
    objectclass: organizationalUnit
    objectclass: top
    ou: users

    # Entry 7: cn=Bill Gates,ou=users,dc=example,dc=org
    dn: cn=Bill Gates,ou=users,dc=example,dc=org
    cn: Bill Gates
    gidnumber: 500
    givenname: bill
    homedirectory: /home/users/bgates
    objectclass: inetOrgPerson
    objectclass: posixAccount
    objectclass: top
    sn: gates
    uid: bgates
    uidnumber: 1000
    mail: bgates@example.org
    userPrincipalName: bgates@example.org
    userpassword: {MD5}ICy5YqxZB1uWSwcVLSNLcA==

    # Entry 8: cn=Ivan Franchin,ou=users,dc=example,dc=org
    dn: cn=Ivan Franchin,ou=users,dc=example,dc=org
    cn: Ivan Franchin
    gidnumber: 501
    givenname: Ivan
    homedirectory: /home/users/ifranchin
    objectclass: inetOrgPerson
    objectclass: posixAccount
    objectclass: top
    sn: Franchin
    uid: ifranchin
    uidnumber: 1003
    mail: ifranchin@example.org
    userPrincipalName: ifranchin@example.org
    userpassword: {MD5}ICy5YqxZB1uWSwcVLSNLcA==

    # Entry 9: cn=Mark Cuban,ou=users,dc=example,dc=org
    dn: cn=Mark Cuban,ou=users,dc=example,dc=org
    cn: Mark Cuban
    gidnumber: 500
    givenname: Mark
    homedirectory: /home/users/mcuban
    objectclass: inetOrgPerson
    objectclass: posixAccount
    objectclass: top
    sn: Cuban
    uid: mcuban
    uidnumber: 1002
    mail: mcuban@example.org
    userPrincipalName: mcuban@example.org
    userpassword: {MD5}ICy5YqxZB1uWSwcVLSNLcA==

    # Entry 10: cn=Steve Jobs,ou=users,dc=example,dc=org
    dn: cn=Steve Jobs,ou=users,dc=example,dc=org
    cn: Steve Jobs
    gidnumber: 500
    givenname: Steve
    homedirectory: /home/users/sjobs
    objectclass: inetOrgPerson
    objectclass: posixAccount
    objectclass: top
    sn: Jobs
    uid: sjobs
    uidnumber: 1001
    mail: sjobs@example.org
    userPrincipalName: sjobs@example.org
    userpassword: {MD5}ICy5YqxZB1uWSwcVLSNLcA==

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  ports:
  - name: ldap
    port: 1389
    protocol: TCP
    targetPort: 1389
  selector:
    app: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - image: bitnami/openldap:latest
        imagePullPolicy: IfNotPresent
        name: openldap
        volumeMounts:
        - name: openldapconfig
          mountPath: "/ldifs/users.ldif"
          subPath: users.ldif
        - name: openldapconfig
          mountPath: "/opt/bitnami/openldap/etc/schema/inetorgperson.ldif"
          subPath: inetorgperson.ldif
      volumes:
        - name: openldapconfig
          configMap:
            name: openldapconfig          
