{
 "title": "Astra Business Metrics [INTERNAL]",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AccountName", "label": "Account Name", "query": { "query": "label_values(account_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Accounts Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(max by (account_id,account_name) (max_over_time(astra_nautilus_app_v6{}[1d])))"
    }
   ]
  },
  {
   "title": "Total Active Accounts",
   "type": "stat",
   "description": "The accounts with at least one application",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(max by (account_id,account_name) (max_over_time(astra_nautilus_app_v6{}[1d])) > 0)"
    }
   ]
  },
  {
   "title": "Total Premium Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (account_name) (count_over_time(astra_billing_account_total_minutes{terms=\"paid\"}[1h])))"
    }
   ]
  },
  {
   "title": "Total Paid Minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (terms) (max_over_time(astra_billing_account_total_minutes{terms=\"paid\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Activated Users ($AccountName)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (max_over_time(user_total{measurement=\"activated\",service=\"identity\", accountName=~\"$AccountName\"}[1h]))"
    }
   ]
  },
  {
   "title": "Accounts Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Account Details($AccountName)",
     "type": "table",
     "description": "Account vitals",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (accountID,accountName,accountCreationTime,accountCompanyName) (max_over_time(user_total{accountName=~\"$AccountName\", job=\"identity\", measurement=\"registered\"}[1h]))"
      },
      {
       "expr": "sum by (accountID, accountName,accountCreationTime,accountCompanyName) (max_over_time(user_total{accountName=~\"$AccountName\", job=\"identity\", measurement=\"activated\"}[1h]))"
      },
      {
       "expr": "label_replace(sum by (account_id, account_name, terms) (max_over_time (astra_billing_account_total_minutes{account_name=~\"$AccountName\"}[1h])), \"accountID\", \"$1\", \"account_id\", \"(.*)\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All applications ($AccountName)",
     "type": "stat",
     "description": "Total number of applications",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=~\"protected|partial|atRisk|none|clone\"}))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Fully protected ($AccountName)",
     "type": "stat",
     "description": "Number of fully protected applications",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"protected\"}))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Partially protected ($AccountName)",
     "type": "stat",
     "description": "Number of partially protected applications",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"partial\"}))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Not protected ($AccountName)",
     "type": "stat",
     "description": "Number of applications not protected",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"none\"}))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Cloned ($AccountName)",
     "type": "stat",
     "description": "Number of cloned applications",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"clone\"}))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "At risk ($AccountName)",
     "type": "stat",
     "description": "Number of applications at risk",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"atRisk\"}))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Backups ($AccountName)",
     "type": "stat",
     "description": "Number of backups",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (max by (account_id,account_name) (max_over_time(astra_nautilus_backup_v6{account_name=~\"$AccountName\"}[1h])))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Snapshots ($AccountName)",
     "type": "stat",
     "description": "Number of snapshots",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id,account_name,healthy) (max_over_time(astra_nautilus_snapshot_v6{account_name=~\"$AccountName\"}[1h])))",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Application Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Applications ($AccountName)",
     "type": "table",
     "description": "Number of applications defined",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=~\"protected|partial|atRisk|none\"}))"
      },
      {
       "expr": "sum by (account_id, account_name) (max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"protected\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (account_id, account_name) (max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"partial\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (account_id, account_name) (max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"atRisk\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (account_id, account_name) (max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"none\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (account_id, account_name) (max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"clone\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backups ($AccountName)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (account_id, account_name) (max by(account_id, account_name,healthy) (max_over_time(astra_nautilus_backup_v6{account_name=~\"$AccountName\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_backup_v6_info{account_name=~\"$AccountName\", state=\"completed\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_backup_v6_info{account_name=~\"$AccountName\", state=\"failed\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_backup_v6_info{account_name=~\"$AccountName\", state=\"running\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_backup_v6_info{account_name=~\"$AccountName\", state=\"removed\"}[1h])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Snapshots ($AccountName)",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum by (account_id, account_name) (max by (account_id, account_name,healthy) (max_over_time(astra_nautilus_snapshot_v6{account_name=~\"$AccountName\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_snapshot_v6_info{account_name=~\"$AccountName\", state=\"completed\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_snapshot_v6_info{account_name=~\"$AccountName\", state=\"failed\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_snapshot_v6_info{account_name=~\"$AccountName\", state=\"running\"}[1h])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (account_id) (max by (account_id, id) (max_over_time(astra_nautilus_snapshot_v6_info{account_name=~\"$AccountName\", state=\"removed\"}[1h])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Used Volume Capacity by Account",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (account_id,account_name,app) (max by (account_id,account_name,app) (max_over_time(astra_composite_volume_managed_app_avg_used_capacity_bytes{account_name=~\"$AccountName\"}[1h])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Summary & Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespaces Available ($AccountName)",
     "type": "stat",
     "description": "Number of namespaces exist in user's clusters",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"namespace_available\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespaces Available ($AccountName)",
     "type": "table",
     "description": "Number of namespaces associated with namespaces",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "sum by (account_name) (max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"namespace_available\"}))"
      }
     ]
    },
    {
     "title": "Namespaces Associated ($AccountName)",
     "type": "stat",
     "description": "Number of namespaces associated with applications",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name, state)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"namespace_associated\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Associated ($AccountName)",
     "type": "table",
     "description": "Number of namespaces associated with applications",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "expr": "sum by (account_name) (max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"namespace_associated\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Trending",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Accounts",
     "type": "timeseries",
     "description": "Number of total accounts ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "count(max by (account_id,account_name) (max_over_time(astra_nautilus_app_v6{}[1d])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Accounts",
     "type": "timeseries",
     "description": "Number of active accounts which have at least one application",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "expr": "count(max by (account_id,account_name) (max_over_time(astra_nautilus_app_v6{}[1d])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Available ($AccountName)",
     "type": "timeseries",
     "description": "Number of namespaces available",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"namespace_available\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Associated ($AccountName)",
     "type": "timeseries",
     "description": "Number of namespaces associated with at least one application",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "expr": "sum(max by (account_id, account_name)(astra_nautilus_app_v6{account_name=~\"$AccountName\", state=\"namespace_associated\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Cluster Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Managed Cluster Count for GCP ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by () (max by (id) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"managed\",cloud_name=\"GCP\"}[1h])))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Unmanaged Cluster Count for GCP ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by () (max by (id) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"unmanaged\",cloud_name=\"GCP\"}[1h])))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Managed Cluster Count for Azure ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by () (max by (id) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"managed\",cloud_name=\"Azure\"}[1h])))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Unmanaged Cluster Count for Azure ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by () (max by (id) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"unmanaged\",cloud_name=\"Azure\"}[1h])))",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Cluster Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Account's managed Cluster Count For given Cloud ($AccountName)",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by (cloud_name,account_name) (max by (id,cloud_name,account_name) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"managed\"}[1h])))"
      }
     ]
    },
    {
     "title": "Account's Unmanaged Cluster Count For given Cloud ($AccountName)",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 45 },
     "targets": [
      {
       "expr": "sum by (cloud_name,account_name) (max by (id, cloud_name, account_name) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"unmanaged\"}[1h])))"
      }
     ]
    },
    {
     "title": "Managed Cluster's State Count For given Cloud ($AccountName)",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 45 },
     "targets": [
      {
       "expr": "sum by (cloud_name,state) (max by (id,cloud_name,state) (max_over_time(astra_composite_compute_cluster_info{account_name=~\"$AccountName\",managed_state=\"managed\"}[1h])))"
      }
     ]
    },
    {
     "title": "Account's managed Cluster's State Count For given Cloud ($AccountName)",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 45 },
     "targets": [
      {
       "expr": "sum by (cloud_name,state,account_name) (max by (id,cloud_name,state,account_name) (max_over_time(astra_composite_compute_cluster_info{account_name=~\".*\",managed_state=\"managed\"}[1h])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volume Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume Total Allocated ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id,account_name,app) (max_over_time(astra_composite_volume_total_allocated_storage_bytes{account_name=~\"$AccountName\"}[1h])))/1000000000",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Sum of Average Used PV Capacity ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 9, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id,account_name,app) (max_over_time(astra_composite_volume_managed_app_avg_used_capacity_bytes{account_name=~\"$AccountName\"}[1h])))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Volume Count ($AccountName)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(max by (account_id,account_name,app) (max_over_time(astra_composite_volume_total_volume_counts{account_name=~\"$AccountName\"}[1h])))",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volume Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Allocated Storage ($AccountName)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (account_id,account_name,app) (max by (account_id,account_name,app) (max_over_time(astra_composite_volume_total_allocated_storage_bytes{account_name=~\"$AccountName\"}[1h])))"
      }
     ]
    },
    {
     "title": "Average Used PV Capacity (\"$AccountName\")",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (account_id,account_name,app) (max by (account_id,account_name,app) (max_over_time(astra_composite_volume_managed_app_avg_used_capacity_bytes{account_name=~\".+\"}[1h])))"
      }
     ]
    },
    {
     "title": "Volume Counts ($AccountName)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (account_id,account_name,app) (max by (account_id,account_name,app) (max_over_time(astra_composite_volume_total_volume_counts{account_name=~\".+\"}[1h])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Credentials Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Credential Counts for every account",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sum by (accountID,accountName, valid) (max_over_time(credential_count[1h]))"
      }
     ]
    },
    {
     "title": "Credential Counts for every account at a given creation timestamp",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 101 },
     "targets": [
      {
       "expr": "sum by (accountID,accountName, valid,creationTimestamp) (max_over_time(credential_count[1h]))"
      }
     ]
    }
   ]
  }
 ]
}