apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: neptune-system
spec:
  astraConnect:
    image: astra-connector:latest
  nats:
    image: nats:2.8.4-alpine3.15
  astra:
    accountId: <ASTRA_ACCOUNT_ID>
    clusterName: neptune-cluster
    skipTLSValidation: true
    tokenRef: astra-token
  natsSyncClient:
    cloudBridgeURL: <ASTRA_HOST_URL>
    hostAliasIP: <ASTRA_HOST_ALIAS_IP>
    image: natssync-client:2.1.202309262120
  imageRegistry:
    name: kind-registry:5001
    secret:
