apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: astra-connector
spec:
  astraConnect:
    image: latest
  astra:
    accountId: <ASTRA_ACCOUNT_ID>
    clusterName: neptune-cluster
    skipTLSValidation: true
    tokenRef: astra-token
  natsSyncClient:
    cloudBridgeURL: <ASTRA_HOST_URL>
    hostAliasIP: <ASTRA_HOST_ALIAS_IP>
  imageRegistry:
    name: kind-registry:5001
  neptune:
    image: latest
  skipPreCheck: true