apiVersion: astra.netapp.io/v1
kind: AstraConnector
metadata:
  name: astra-connector
  namespace: neptune-system
spec:
  astra:
    accountId: <ASTRA_ACCOUNT_ID>
    clusterName: neptune-cluster
    skipTLSValidation: true
    tokenRef: astra-token
  natsSyncClient:
    cloudBridgeURL: <ASTRA_HOST_URL>
    hostAliasIP: <ASTRA_HOST_ALIAS_IP>
  imageRegistry:
    name: netappdownloads.jfrog.io/docker-astra-control-staging/arch30/neptune
    secret: regcred