allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- DAC_READ_SEARCH
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  creationTimestamp: "2024-01-21T07:40:20Z"
  generation: 1
  labels:
    app.netapp.io/managed-by: astra.netapp.io
  name: netapp-astra-backup
  resourceVersion: "7991037"
  uid: 066b4af0-e697-4683-ba3d-104c6e4830ee
priority: 1
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2024-01-21T07:40:20Z"
  labels:
    app.netapp.io/managed-by: astra.netapp.io
  name: netapp-astra-backup
  resourceVersion: "7991038"
  uid: 84301f05-26e8-438e-8125-ac34db192300
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - netapp-astra-backup
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {SCCNAME}-{NAMESPACE}
  namespace: {NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {SCCNAME}
subjects:
- kind: ServiceAccount
  name: netapp-astra-backup
  namespace: {NAMESPACE}
