---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tridentversions.trident.netapp.io
spec:
  conversion:
    strategy: None
  group: trident.netapp.io
  names:
    categories:
    - trident
    - trident-internal
    kind: TridentVersion
    listKind: TridentVersionList
    plural: tridentversions
    shortNames:
    - tver
    - tversion
    singular: tridentversion
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The Trident version
      jsonPath: .trident_version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tridentorchestrators.trident.netapp.io
spec:
  group: trident.netapp.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  names:
    kind: TridentOrchestrator
    listKind: TridentOrchestratorList
    plural: tridentorchestrators
    singular: tridentorchestrator
    shortNames:
    - torc
    - torchestrator
  scope: Cluster
