name: Multiarch build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

env:
  IMAGE_NAME: astra3dt
  IMAGE_TAG: v0.1.0
  DH_REGISTRY: docker.io
  DH_NAMESPACE: tli551
  GH_REGISTRY: ghcr.io
  GH_NAMESPACE: litong01/astra

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v4
        
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_KEY }}

      - name: build and push images
        run: |
          docker buildx build --push \
            --tag ${{ env.DH_REGISTRY }}/${{env.DH_NAMESPACE }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
            --platform linux/amd64,linux/arm64 .

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_KEY }}
          repository: ${{env.DH_NAMESPACE }}/${{env.IMAGE_NAME}}

      - name: login to Github package
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ secrets.GHP_USER }}
          password: ${{ secrets.GHP_KEY }}

      - name: build and push images
        run: |
          docker buildx build --push \
            --tag ${{ env.GH_REGISTRY }}/${{env.GH_NAMESPACE }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
            --platform linux/amd64,linux/arm64 .
